name: e2e

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DATABASE_URL_NEWS: "postgresql://testuser:testpw@db:5432/newsdb"
  
jobs:

  build:

    runs-on: ubuntu-22.04

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: newsdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        volumes:
          # copy sql script to create tables
          - ${GITHUB_WORKSPACE}/sql:/docker-entrypoint-initdb.d
          
    steps:
    - uses: actions/checkout@v3
    - name: Init db
      working-directory: ./server
      run: npx prisma db push
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        start: |
          cd server; yarn dev
          yarn start
        wait-on: "http://localhost:3000"

